version: "3.8"
services:
  caching:
    container_name: redis 
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb --maxmemory-policy allkeys-lru
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - caching
    environment:
      - REDIS_HOST=caching
      - POSTGRESQL_HOST=postgresql
      - SERVER_HOST=server
    ports:
      - "3000:3000"
    volumes:
      - ./client/main.js:/app/index.js
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "50051:50051"
    environment:
      - POSTGRESQL_HOST=postgresql
      - SERVER_HOST=server
  postgresql:
    container_name: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=uwu
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=123
  redis-commander:
    container_name: rediscommander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=caching
    ports:
        - 8081:8081
