version: '2.2'

networks:
  app-tier:
    driver: bridge

services:
  cassandra-node1:
    image: bitnami/cassandra:latest
    volumes:
      - './cql:/docker-entrypoint-initdb.d'
    networks:
      - app-tier   
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXNzYW5kcmEiOiJjdWxpYSJ9.fc6sW-Gx4RmJ6mGDTL-f6WsH6VZIj_s4NyTIFIrdGvY

  cassandra-node2:
    image: bitnami/cassandra:latest
    networks:
      - app-tier
    depends_on:
      - cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXNzYW5kcmEiOiJjdWxpYSJ9.fc6sW-Gx4RmJ6mGDTL-f6WsH6VZIj_s4NyTIFIrdGvY

  cassandra-node3:
    image: bitnami/cassandra:latest
    networks:
      - app-tier
    depends_on:
      - cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXNzYW5kcmEiOiJjdWxpYSJ9.fc6sW-Gx4RmJ6mGDTL-f6WsH6VZIj_s4NyTIFIrdGvY
  api:
    build: ./apiRest
    volumes:
      - './apiRest/index.js:/usr/src/app/index.js'
    networks:
      - app-tier
    ports:
      - "3000:3000"